// angular-app/src/app/features/profile/profile.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { InputNumberModule } from 'primeng/inputnumber';
import { DropdownModule } from 'primeng/dropdown';
import { CheckboxModule } from 'primeng/checkbox';
import { TableModule } from 'primeng/table';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { ApiService } from '../../core/services/api.service';
import { QuizService } from '../../core/services/quiz.service';
import {
  StudentProfile,
  PerformanceBucket,
} from '../../models/student.model';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    CardModule,
    ButtonModule,
    InputTextModule,
    InputNumberModule,
    DropdownModule,
    CheckboxModule,
    TableModule,
    ToastModule,
  ],
  providers: [MessageService],
  template: `
    <p-toast></p-toast>

    @if (!quiz.currentStudent()) {
      <p-card header="Profile">
        <p class="text-500">Select a student from the header dropdown to view their profile.</p>
      </p-card>
    } @else if (loading()) {
      <p class="text-500">Loading profile...</p>
    } @else if (profile()) {
      <div class="grid">
        <!-- Edit form -->
        <div class="col-12 md:col-6">
          <p-card header="Edit Profile">
            <div class="flex flex-column gap-3">
              <div class="flex flex-column gap-1">
                <label class="font-semibold">Name</label>
                <input pInputText [(ngModel)]="name" class="w-full" />
              </div>
              <div class="flex gap-3">
                <div class="flex flex-column gap-1 flex-1">
                  <label class="font-semibold">Age</label>
                  <p-inputNumber
                    [(ngModel)]="age"
                    [min]="4"
                    [max]="120"
                    [showButtons]="true"
                    [useGrouping]="false"
                  ></p-inputNumber>
                </div>
                <div class="flex flex-column gap-1 flex-1">
                  <label class="font-semibold">Gender</label>
                  <p-dropdown
                    [options]="genderOptions"
                    [(ngModel)]="gender"
                    optionLabel="label"
                    optionValue="value"
                    placeholder="—"
                    [showClear]="true"
                  ></p-dropdown>
                </div>
              </div>
              <div class="flex flex-column gap-1">
                <label class="font-semibold">Learned Timetables</label>
                <div class="flex flex-wrap gap-2">
                  @for (n of timetableRange; track n) {
                    <div class="flex align-items-center gap-1">
                      <p-checkbox
                        [inputId]="'ptt-' + n"
                        [value]="n"
                        [(ngModel)]="learnedTimetables"
                      ></p-checkbox>
                      <label [for]="'ptt-' + n" class="text-sm">{{ n }}</label>
                    </div>
                  }
                </div>
              </div>
              <p-button
                label="Save"
                icon="pi pi-save"
                (onClick)="save()"
                [disabled]="saving() || !name.trim() || learnedTimetables.length === 0"
                [loading]="saving()"
              ></p-button>
            </div>
          </p-card>
        </div>

        <!-- Performance stats -->
        <div class="col-12 md:col-6">
          <p-card header="Performance">
            @if (profile()!.stats) {
              <h4 class="mt-0">Overall</h4>
              <ng-container *ngTemplateOutlet="bucketTpl; context: { $implicit: profile()!.stats.overall }"></ng-container>

              @for (bucket of profile()!.stats.by_quiz_type; track bucket.quiz_type_code) {
                <h4>{{ bucket.quiz_type_description }}</h4>
                <ng-container *ngTemplateOutlet="bucketTpl; context: { $implicit: bucket }"></ng-container>
              }
            }
          </p-card>
        </div>
      </div>

      <ng-template #bucketTpl let-b>
        <div class="grid text-sm">
          <div class="col-6">Sessions:</div><div class="col-6 font-semibold">{{ b.sessions }}</div>
          <div class="col-6">Completed:</div><div class="col-6 font-semibold">{{ b.completed_sessions }}</div>
          <div class="col-6">Questions:</div><div class="col-6 font-semibold">{{ b.total_questions }}</div>
          <div class="col-6">Correct:</div><div class="col-6 font-semibold text-green-600">{{ b.correct_answers }}</div>
          <div class="col-6">Wrong:</div><div class="col-6 font-semibold text-red-600">{{ b.wrong_answers }}</div>
          <div class="col-6">Avg Score:</div><div class="col-6 font-semibold">{{ b.average_score_percent }}%</div>
        </div>
      </ng-template>
    }
  `,
})
export class ProfileComponent implements OnInit {
  private api = inject(ApiService);
  protected quiz = inject(QuizService);
  private messageService = inject(MessageService);

  loading = signal(true);
  saving = signal(false);
  profile = signal<StudentProfile | null>(null);

  name = '';
  age: number | null = null;
  gender: string | null = null;
  learnedTimetables: number[] = [];

  timetableRange = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  genderOptions = [
    { label: 'Female', value: 'female' },
    { label: 'Male', value: 'male' },
    { label: 'Other', value: 'other' },
    { label: 'Prefer not to say', value: 'prefer_not_say' },
  ];

  ngOnInit() {
    this.loadProfile();
  }

  loadProfile() {
    const id = this.quiz.currentStudentId();
    if (!id) {
      this.loading.set(false);
      return;
    }
    this.api.getStudent(id).subscribe({
      next: (p) => {
        this.profile.set(p);
        this.name = p.name;
        this.age = p.age;
        this.gender = p.gender;
        this.learnedTimetables = [...p.learned_timetables];
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }

  save() {
    const id = this.quiz.currentStudentId();
    if (!id) return;
    this.saving.set(true);

    this.api
      .updateStudent(id, {
        name: this.name.trim(),
        age: this.age,
        gender: this.gender,
        learned_timetables: this.learnedTimetables,
      })
      .subscribe({
        next: () => {
          this.saving.set(false);
          this.quiz.refreshStudents();
          this.messageService.add({
            severity: 'success',
            summary: 'Saved',
            detail: 'Profile updated successfully.',
          });
          this.loadProfile();
        },
        error: () => {
          this.saving.set(false);
          this.messageService.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Failed to update profile.',
          });
        },
      });
  }
}

// nuxt-app/app/pages/profile.vue
<template>
  <main class="page">
    <h1>Profile</h1>

    <section class="card">
      <p v-if="!selectedStudentId" class="hint">Select an active student in the top bar to edit profile preferences.</p>

      <template v-if="selectedStudentId">
        <label>
          Name
          <BaseInput v-model="name" type="text" />
        </label>

        <label>
          Age
          <BaseInput v-model.number="age" type="number" min="4" max="120" />
        </label>

        <label>
          Gender
          <select v-model="gender" class="input">
            <option value="">Prefer not to say</option>
            <option value="female">Female</option>
            <option value="male">Male</option>
            <option value="other">Other</option>
          </select>
        </label>

        <fieldset class="tables-fieldset">
          <legend>Learned timetables (1–10)</legend>
          <div class="tables-grid">
            <label v-for="table in timetableOptions" :key="table" class="table-option">
              <input v-model="learnedTimetables" type="checkbox" :value="table" />
              <span>{{ table }}</span>
            </label>
          </div>
        </fieldset>

        <BaseButton type="button" :disabled="saving" @click="saveProfile">
          {{ saving ? "Saving..." : "Save profile" }}
        </BaseButton>

        <section class="stats-block">
          <h2>Performance (All quizzes)</h2>
          <div class="stats-grid">
            <p><strong>Sessions:</strong> {{ profileStats.overall.sessions }}</p>
            <p><strong>Completed:</strong> {{ profileStats.overall.completed_sessions }}</p>
            <p><strong>In progress:</strong> {{ profileStats.overall.in_progress_sessions }}</p>
            <p><strong>Total questions:</strong> {{ profileStats.overall.total_questions }}</p>
            <p><strong>Correct / Wrong:</strong> {{ profileStats.overall.correct_answers }} / {{ profileStats.overall.wrong_answers }}</p>
            <p><strong>Average score:</strong> {{ formatPercent(profileStats.overall.average_score_percent) }}</p>
            <p><strong>Total time spent:</strong> {{ formatDuration(profileStats.overall.total_time_seconds) }}</p>
          </div>
        </section>

        <section class="stats-block">
          <h2>Performance by quiz type</h2>
          <table v-if="profileStats.by_quiz_type.length > 0" class="stats-table">
            <thead>
              <tr>
                <th>Quiz type</th>
                <th>Sessions</th>
                <th>Completed</th>
                <th>In progress</th>
                <th>Avg score</th>
                <th>Total time</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in profileStats.by_quiz_type" :key="row.quiz_type_code">
                <td>{{ row.quiz_type_description }} ({{ row.quiz_type_code }})</td>
                <td>{{ row.sessions }}</td>
                <td>{{ row.completed_sessions }}</td>
                <td>{{ row.in_progress_sessions }}</td>
                <td>{{ formatPercent(row.average_score_percent) }}</td>
                <td>{{ formatDuration(row.total_time_seconds) }}</td>
              </tr>
            </tbody>
          </table>
          <p v-else class="hint">No quiz data yet.</p>
        </section>
      </template>

      <p v-if="message" :class="messageType === 'error' ? 'error' : 'success'">{{ message }}</p>
    </section>
  </main>
</template>

<script setup lang="ts">
const api = useApi()

const selectedStudentId = useState<string>("currentStudentId", () => "")
const studentsDirectory = useState<Array<{ id: string; name: string }>>("studentsDirectory", () => [])
const name = ref("")
const age = ref<number | null>(null)
const gender = ref<"female" | "male" | "other" | "prefer_not_say" | "">("")
const learnedTimetables = ref<number[]>([])
const saving = ref(false)
const message = ref("")
const messageType = ref<"success" | "error">("success")
const profileStats = ref({
  overall: {
    quiz_type_code: "all",
    quiz_type_description: "All quiz types",
    sessions: 0,
    completed_sessions: 0,
    in_progress_sessions: 0,
    total_questions: 0,
    correct_answers: 0,
    wrong_answers: 0,
    average_score_percent: 0,
    total_time_seconds: 0,
  },
  by_quiz_type: [] as Array<{
    quiz_type_code: string
    quiz_type_description: string
    sessions: number
    completed_sessions: number
    in_progress_sessions: number
    total_questions: number
    correct_answers: number
    wrong_answers: number
    average_score_percent: number
    total_time_seconds: number
  }>,
})
const timetableOptions = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

function formatPercent(value: number): string {
  return `${value.toFixed(2)}%`
}

function pad2(value: number): string {
  return String(value).padStart(2, "0")
}

function formatDuration(totalSeconds: number): string {
  if (totalSeconds <= 0) {
    return "0s"
  }

  if (totalSeconds < 60) {
    return `${totalSeconds}s`
  }

  if (totalSeconds < 3600) {
    const minutes = Math.floor(totalSeconds / 60)
    const seconds = totalSeconds % 60
    return `${pad2(minutes)}:${pad2(seconds)}`
  }

  const hours = Math.floor(totalSeconds / 3600)
  const minutes = Math.floor((totalSeconds % 3600) / 60)
  const seconds = totalSeconds % 60
  return `${pad2(hours)}:${pad2(minutes)}:${pad2(seconds)}`
}

async function onStudentChange() {
  message.value = ""

  if (!selectedStudentId.value) {
    name.value = ""
    age.value = null
    gender.value = ""
    learnedTimetables.value = []
    profileStats.value = {
      overall: {
        quiz_type_code: "all",
        quiz_type_description: "All quiz types",
        sessions: 0,
        completed_sessions: 0,
        in_progress_sessions: 0,
        total_questions: 0,
        correct_answers: 0,
        wrong_answers: 0,
        average_score_percent: 0,
        total_time_seconds: 0,
      },
      by_quiz_type: [],
    }
    return
  }

  try {
    const profile = await api.getStudentProfile(selectedStudentId.value)
    name.value = profile.name
    age.value = profile.age
    gender.value = profile.gender ?? ""
    learnedTimetables.value = profile.learned_timetables
    profileStats.value = profile.stats
  } catch {
    messageType.value = "error"
    message.value = "Could not load student profile."
  }
}

watch(selectedStudentId, () => {
  onStudentChange()
}, { immediate: true })

async function saveProfile() {
  if (!selectedStudentId.value) {
    return
  }

  if (name.value.trim().length === 0) {
    messageType.value = "error"
    message.value = "Name is required."
    return
  }

  if (learnedTimetables.value.length === 0) {
    messageType.value = "error"
    message.value = "Select at least one learned timetable."
    return
  }

  saving.value = true
  message.value = ""

  try {
    const updated = await api.updateStudentProfile(selectedStudentId.value, {
      name: name.value.trim(),
      age: age.value,
      gender: gender.value || null,
      learned_timetables: learnedTimetables.value,
    })

    name.value = updated.name
    age.value = updated.age
    gender.value = updated.gender ?? ""
    learnedTimetables.value = updated.learned_timetables

    studentsDirectory.value = studentsDirectory.value.map((student) =>
      student.id === updated.id ? { ...student, name: updated.name } : student
    )

    messageType.value = "success"
    message.value = "Profile saved."
  } catch {
    messageType.value = "error"
    message.value = "Could not save profile."
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.page {
  max-width: 40rem;
  margin: 2rem auto;
  padding: 0 1rem;
  display: grid;
  gap: 1rem;
}

.card {
  border: 1px solid #e2e8f0;
  border-radius: 0.75rem;
  padding: 1rem;
  display: grid;
  gap: 1rem;
}

.input {
  width: 100%;
  border: 1px solid #cbd5e1;
  border-radius: 0.5rem;
  padding: 0.55rem 0.7rem;
  font-size: 1rem;
  background: #fff;
}

.hint {
  color: #475569;
}

.tables-fieldset {
  border: 1px solid #e2e8f0;
  border-radius: 0.5rem;
  padding: 0.75rem;
  display: grid;
  gap: 0.5rem;
}

.tables-grid {
  display: grid;
  grid-template-columns: repeat(5, minmax(0, 1fr));
  gap: 0.5rem;
}

.table-option {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
}

.error {
  color: #dc2626;
}

.success {
  color: #166534;
}

.stats-block {
  border-top: 1px solid #e2e8f0;
  padding-top: 0.75rem;
  display: grid;
  gap: 0.75rem;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.5rem 0.75rem;
}

.stats-table {
  width: 100%;
  border-collapse: collapse;
}

.stats-table th,
.stats-table td {
  border-bottom: 1px solid #e2e8f0;
  padding: 0.5rem;
  text-align: left;
}
</style>
